### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by ghost** [bandya2003/CRM-Website#1]
Hi there,

I am a beginner in open-source projects. How can I contribute to this one?

The least I can think of is making a banner for the readme.md

**Comment by RAJEEVKUMAR9598** [comment]
Hii Sir !! can i contribute here please.sir assign me this task!! give me label please.

**Comment by RAJEEVKUMAR9598** [comment]
@bandya2003 sir can i give css code??

**Comment by bandya2003** [comment]
> 
Sure you can work on it
