### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by asifStar135** [bandya2003/CRM-Website#24]
I'll love to create a simple and functional web-app which can convert between different temperature units.

**Comment by bandya2003** [comment]
> I'll love to create a simple and functional web-app which can convert between different temperature units.

Sure , work on it @AsifStar786

**Comment by Serajhub** [comment]
hay i have create simple temperature converter. can u please assign this project to me

**Comment by Serajhub** [comment]
hay i have create simple temperature converter. can u please assign this project to me
